01.Presentation/WebApp/Controllers/DemandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

using BE = BusinessEntities;
using SVC = MongoDB.Service;

namespace WebApp.Controllers
{

    [Authorize]
    public class DemandController : Controller
    {
        private readonly SVC.IBookService bookService;
        private readonly SVC.IUserService userService;
        private readonly SVC.IDemandService demandService;
        private readonly Models.IApiClient<BE.Book> apiClient;

        public DemandController(SVC.IBookService bookService,
            SVC.IUserService userService,
            SVC.IDemandService demandService,
            Models.IApiClient<BE.Book> apiClient)
        {
            this.bookService = bookService;
            this.userService = userService;
            this.demandService = demandService;
            this.apiClient = apiClient;
        }

        public async Task<ActionResult> MyDemands(bool IsAfterDelete = false)
        {
            //Show deleted alert for user
            if (IsAfterDelete)
                ViewBag.Status = "DeleteSuccess";

            //ViewBag.Message = "My Demands";
            var demands = await demandService.GetByUser(User.Identity.Name);

            return View(demands.ToList());
        }

        public ActionResult BooksDemand()
        {
            ViewBag.Message = "Books Demand";

            return View();
        }

        public async Task<ActionResult> Delete(string id)
        {
            ViewBag.Message = "Delete Demand";

            var demand = await demandService.Get(id);

            return View(demand);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteDemand(string id)
        {
            var demand = await demandService.Delete(id);

            //IsAfterDelete = true will notify to user about the success
            return RedirectToAction("MyDemands", new { IsAfterDelete = true });
        }

        #region Partial Views

        /// <summary>
        /// Get books from api
        /// </summary>
        /// <param name="query">filter query</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> SearchBooks(string query)
        {
            var books = await apiClient.Search("api/Books" + (string.IsNullOrEmpty(query) ? "/Get" : "/Get?filter=" + query));
            return PartialView("_BooksRearchResult", books);
        }

        /// <summary>
        /// Get book demands by Ids
        /// </summary>
        /// <param name="bookIds">Demand Ids separated by comma(',')</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> BooksDemand(string bookIds)
        {

            //Avoid empty string and To the list
            var IdList = bookIds.Split(',').Select(s => s).Where(w => !string.IsNullOrEmpty(w)).ToList();

            if (IdList.Count > 0)
            {
                var books = await bookService.GetByIds(IdList);

                if (books.Count() > 0)
                {
                    //User Object For Book Demand
                    var user = await userService.GetByUserName(User.Identity.Name);

                    foreach (var book in books)
                    {
                        //Insert books for DB
                        await demandService.Insert(new BE.Demand() { Book = book, User = user });
                    }

                    //Success msg for user alert
                    ViewBag.Status = "Success";
                    return PartialView("_BookDemand", books.ToList());
                }
                else
                {
                    //NotSelected msg for user alert
                    ViewBag.Status = "NotSelected";
                    return PartialView("_BookDemand", null);
                }

            }
            else
            {
                //NotSelected msg for user alert
                ViewBag.Status = "NotSelected";
                return PartialView("_BookDemand", null);
            }

        }

        #endregion

    }
}

01.Presentation/WebApp/Views/Shared/_BookDemand.cshtml
@model IList<BusinessEntities.Book>

<div class="row">
    @{
        if (ViewBag.Status == "Success")
        {
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok-sign"></span><strong>Success!</strong>&nbsp;Book demand successfully completed!</div>
        }
        else if (ViewBag.Status == "NotSelected")
        {
            <div class="alert alert-warning"><span class="glyphicon glyphicon-warning-sign"></span><strong>Please select books!</strong>&nbsp;Please select few books before demand!</div>
        }
        else
        {
            <div class="alert alert-danger"><span class="glyphicon glyphicon-exclamation-sign"></span><strong>Error!</strong>&nbsp;Error at book demand saving! Please try again&nbsp;<a href="../Demand/BooksDemand">Go to books demand</a></div>
        }
    }

</div>

@if (Model != null && Model.Count() > 0)
{
    <div class="panel panel-default">

        <div class="panel-heading">
            <h4>Following @Model.Count() book(s) are successfully demanded.</h4>
        </div>
        <div class="panel-body">

            <table id="books" class="table select-checkbox">
                <thead>
                    <tr>
                        <th width="35%">Title</th>
                        <th width="10%">Description</th>
                        <th width="20%">Publisher</th>
                        <th width="20%">Authors</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var book in Model)
                    {
                        <tr>
                            <td>@book.Title</td>
                            <td>
                                <button id="viewDescription" onclick='showHideDescription("@book.Id",this)' value="View" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span></button>
                            </td>
                            <td>@book.Publisher</td>
                            <td>
                                @foreach (var author in book.Authors)
                                {
                                    <span> @author </span>
                                }
                            </td>
                        </tr>
                        <tr style="display:none" id="@book.Id">
                            <td colspan="5">
                                <div class="row">
                                    <div class="col-sm-12 col-lg-12 col-xs-12">
                                        <h5><strong>Book Description</strong></h5>
                                        <p class="alert alert-warning">@book.Description</p>
                                    </div>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>

            </table>

        </div>
    </div>

        <script>

            $(function () {

                //Clear the selected books and search content when reload the demand status
                $("#selectedBooks").hide();
                $("#bookIds").val();
                $("#query").val();

            });

            function showHideDescription(bookId, btn) {

                $(btn).find('span').toggleClass('glyphicon-plus-sign glyphicon-minus-sign');
                $(btn).toggleClass('btn-success btn-warning');

                if ($("#" + bookId).css('display') === 'none') {
                    $("#" + bookId).show();

                } else {

                    $("#" + bookId).hide();
                }

            }

        </script>

}

01.Presentation/WebApp/Views/Shared/_BooksRearchResult.cshtml
@model IList<BusinessEntities.Book>

@if (Model == null || Model.Count() == 0)
{
    <div class="alert alert-warning">
        <span class="glyphicon glyphicon-exclamation-sign"></span>&nbsp;<strong>We are sorry!</strong>&nbsp;No books matched with your search query.
    </div>
}
else
{
    <div class="panel panel-default">

        <div class="panel-heading">
            <h4>@Model.Count() Book(s) found</h4>
        </div>
        <div class="panel-body">

            <table id="books" class="table select-checkbox">
                <thead>
                    <tr>
                        <th width="5%">Select</th>
                        <th width="35%">Title</th>
                        <th width="10%">Description</th>
                        <th width="20%">Publisher</th>
                        <th width="20%">Authors</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var book in Model)
                    {
                        <tr id="tr_@book.Id" class="alert">
                            <td><input type="checkbox" id="chk_@book.Id" onclick='selectRow("@book.Id",this)' /></td>
                            <td>@book.Title</td>
                            <td>
                                <button id="viewDescription" href="#" onclick='showHideDescription("@book.Id",this)' value="View" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span></button>
                            </td>
                            <td>@book.Publisher</td>
                            <td>
                                @foreach (var author in book.Authors)
                                {
                                    <span> @author </span>
                                }
                            </td>
                        </tr>
                        <tr style="display:none" id="@book.Id">
                            <td colspan="5">
                                <div class="row">
                                    <div class="col-sm-12 col-lg-12 col-xs-12">
                                        <h5><strong>Book Description</strong></h5>
                                        <p class="alert alert-warning">@book.Description</p>
                                    </div>
                                </div>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>

    <script>

        var bookIds = [];

        function showHideDescription(bookId, btn) {

            $(btn).find('span').toggleClass('glyphicon-plus-sign glyphicon-minus-sign');
            $(btn).toggleClass('btn-success btn-warning');

            if ($("#" + bookId).css('display') === 'none') {
                $("#" + bookId).show();

            } else {

                $("#" + bookId).hide();
            }

        }

        function selectRow(bookId, chk) {

            $("#tr_" + bookId).toggleClass('alert alert-success');
            var rows = $('#books tbody tr.alert-success').length;
            $("#bookCount").text(rows > 0 ? "You have selected " + rows + " Book(s) for demand" : "");

            if (rows > 0) {

                $("#selectedBooks").show();
                $("#selectedBooks").addClass("panel panel-default");

            }
            else {

                $("#selectedBooks").hide();
            }

            if (chk.checked) {

                bookIds.push(bookId);

                $("#bookIds").val(bookIds);

            } else {

                var tempBookIds = [];

                for (var i = 0; i < bookIds.length; i++) {

                    if (bookId !== bookIds[i]) {

                        tempBookIds.push(bookIds[i]);

                    }
                }

                bookIds = tempBookIds;
            }

        }

    </script>

}

01.Presentation/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Demand App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Books demand app", "BooksDemand", "Demand", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Demand Books", "BooksDemand", "Demand")</li>
                    <li>@Html.ActionLink("My Demands", "MyDemands", "Demand")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr class="col-md-12" />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book demand App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.8.1/bootstrap-table.min.js"></script>

</body>
</html>

01.Presentation/WebApp/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <title>@ViewBag.Title - Book Demand App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr class="col-md-12" />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Demand App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>